baseURL = "https://teddykoker.netlify.com/"
languageCode = "en-us"
title = "Teddy Koker"
theme = "hugo-theme-basic"
enableEmoji = true
copyright = "© 2019 Teddy Koker"


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":wave:"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"
[[params.menu]]
  name = "tags"
  url = "tags/"
[[params.menu]]
  name = "about"
  url = "about/"
[[params.menu]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/tomkoker/"
[[params.menu]]
  name = "github"
  url = "https://github.com/teddykoker"